default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    - id: isort
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: flake8
      name: flake8
      entry: flake8