version: '3.1'

services:
  redis:
    image: redis:alpine
    restart: always

  app:
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis