version: '3.1'

services:
  redis:
    image: redis:alpine

  app:
    build: .
    ports:
      - 8080:8080

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
    expose:
      - "25"